services:
  - type: web
    name: fitsite
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: fitsitecondordb
          property: connectionString
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: fitsitecondordb
          property: connectionString
      - key: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
        value: "false"

databases:
  - name: fitsitecondordb
    databaseName: fitsite
    user: fitsite_user