services:
  - type: web
    name: fitsite
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: fitsite-db
          property: connectionString

databases:
  - name: fitsite-db
    databaseName: fitsite
    user: fitsite_user